# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://vitial.com
title: Senior Care Agency
email: contact@vitial.com
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

app-store-img: App_Store_Badge_en_135x40.svg
play-store-img: google-play-en_60.png

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/javier.lopezc
    shown: true
  - title: twitter
    url: https://twitter.com/zurriago1846bo
    shown: true
  - title: github
    url: https://github.com/javilopezc
    shown: false
  - title: linkedin
    url: https://bo.linkedin.com/in/javierglc
    shown: true